services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - PUID=1000            # set to: id -u
      - PGID=1000            # set to: id -g
      - TZ=Europe/Rome
    volumes:
      - /home/c043/syncthing/data:/config
    ports:
      - "3007:3000"
      - "3008:3001"
    shm_size: "2g"
    restart: unless-stopped
