services:
  db:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: 2014
      POSTGRES_DB: miniflux
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux", "-d", "miniflux"]
      interval: 10s
      timeout: 5s
      retries: 5
  miniflux:
    restart: unless-stopped
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://miniflux:2014@db/miniflux?sslmode=disable
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=2014
      - RUN_MIGRATIONS=1
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
