services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    hostname: ${HOSTNAME}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_BOT_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - TZ=Europe/Rome
    command: --interval 300 --cleanup
    healthcheck:
      test: ["CMD-SHELL", "/watchtower --health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
