services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    hostname: ${HOSTNAME}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:  
      - "5000:8080"
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_BOT_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - TZ=Europe/Rome
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
    command: --http-api-metrics --cleanup
