services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    network_mode: 'host'
    volumes:
      - /home/c043/jellyfin/config:/config
      - /home/c043/jellyfin/cache:/cache
      - type: bind
        source: /mnt/ssd/jellyfin/movies
        target: /media/movies
      - type: bind
        source: /mnt/ssd/jellyfin/series
        target: /media/series
      - type: bind
        source: /mnt/ssd/jellyfin/udemy
        target: /media/udemy
      - type: bind
        source: /mnt/ssd/jellyfin/Videos
        target: /media/videos
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.123:8096
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
